"""
FIFO (First-In First-Out) Scheduling
=====================================
Dispatching Rule : Process jobs in order of earliest arrival_time.
                   Ties broken by job_id.
Objective        : Comparison based on Total Completion Time  ΣCj
Data Structure   : Queue  (sorted list, processed front-to-back)
Time Complexity  : O(n) for FIFO queue processing
                   O(n log n) including one-time sorting by arrival_time

Updated after presentation feedback:
FIFO itself is O(n), but this implementation first sorts jobs by arrival_time.
Therefore, the implemented complexity including preprocessing is O(n log n).
Space Complexity : O(n)

This version is modified to match Team 7 dataset files:
- Input data structure: list of dictionaries
- Ratio column name: p_over_w_ratio
- Can run directly with small_jobs or large_jobs generated by Team 7 dataset code
"""

import csv
import time


# ──────────────────────────────────────────────
# Helper: Get p_over_w_ratio safely
# ──────────────────────────────────────────────

def get_p_over_w_ratio(job: dict) -> float:
    """
    Return p_over_w_ratio from a job dictionary.

    Team 7 final dataset uses 'p_over_w_ratio'.
    This helper also supports old 'pw_ratio' only for backward compatibility.
    """
    if "p_over_w_ratio" in job:
        return job["p_over_w_ratio"]

    if "pw_ratio" in job:
        return job["pw_ratio"]

    return round(job["processing_time"] / job["priority_weight"], 2)


# ──────────────────────────────────────────────
# Core Algorithm
# ──────────────────────────────────────────────

def fifo(jobs: list[dict]) -> list[dict]:
    """
    Run FIFO scheduling on a list of jobs.

    Parameters
    ----------
    jobs : list of dict
        Each dict must have keys:
            job_id, product, operation_type, processing_time,
            arrival_time, due_date, priority_weight, p_over_w_ratio

    Returns
    -------
    list of dict
        Scheduled results with added fields:
            seq, start_time, completion_time,
            waiting_time, flow_time, tardiness
    """
    # Sort by arrival_time (FIFO queue order); tie-break by job_id
    queue = sorted(jobs, key=lambda j: (j["arrival_time"], j["job_id"]))

    current_time = 0
    results = []

    for seq, job in enumerate(queue, start=1):
        start = max(current_time, job["arrival_time"])
        end = start + job["processing_time"]
        current_time = end

        results.append({
            "seq": seq,
            "job_id": job["job_id"],
            "product": job["product"],
            "operation_type": job["operation_type"],
            "processing_time": job["processing_time"],
            "arrival_time": job["arrival_time"],
            "due_date": job["due_date"],
            "priority_weight": job["priority_weight"],
            "p_over_w_ratio": get_p_over_w_ratio(job),
            "start_time": start,
            "completion_time": end,
            "waiting_time": start - job["arrival_time"],
            "flow_time": end - job["arrival_time"],
            "tardiness": max(0, end - job["due_date"]),
        })

    return results


# ──────────────────────────────────────────────
# Metrics Helper
# ──────────────────────────────────────────────

def compute_metrics(results: list[dict]) -> dict:
    """
    Compute summary metrics for FIFO results.
    """
    n = len(results)

    return {
        "algorithm": "FIFO",
        "n_jobs": n,
        "total_Cj": sum(r["completion_time"] for r in results),
        "avg_completion_time": round(sum(r["completion_time"] for r in results) / n, 2),
        "avg_waiting_time": round(sum(r["waiting_time"] for r in results) / n, 2),
        "total_flow_time": sum(r["flow_time"] for r in results),
        "avg_flow_time": round(sum(r["flow_time"] for r in results) / n, 2),
        "total_tardiness": sum(r["tardiness"] for r in results),
        "tardy_jobs": sum(1 for r in results if r["tardiness"] > 0),
        "makespan": max(r["completion_time"] for r in results),

      # [UPDATED after presentation feedback]
      # FIFO queue processing itself is O(n) after the queue order is already prepared.
      # In this implementation, the input list is first sorted by arrival_time to build
      # the FIFO queue order. Therefore, the implemented total complexity including
      # this preprocessing step is O(n log n).
      
        "big_o": "O(n) processing / O(n log n) incl. sort",
    }


# ──────────────────────────────────────────────
# Runner for Team 7 list[dict] dataset
# ──────────────────────────────────────────────

def run_fifo(jobs: list[dict]) -> tuple[list[dict], dict, float]:
    """
    Execute FIFO using a list of job dictionaries.

    This function is recommended for Team 7 final project because
    small_dataset and large_dataset are Python list[dict] data.
    """
    t0 = time.perf_counter()
    results = fifo(jobs)
    runtime = (time.perf_counter() - t0) * 1000

    metrics = compute_metrics(results)
    metrics["runtime_ms"] = round(runtime, 4)

    return results, metrics, round(runtime, 4)


# ──────────────────────────────────────────────
# Optional CSV Loader
# ──────────────────────────────────────────────

def load_jobs_from_csv(filepath: str) -> list[dict]:
    """
    Load job data from CSV.

    Expected ratio column:
        p_over_w_ratio

    For backward compatibility, old column name 'pw_ratio' is also accepted.
    """
    jobs = []

    with open(filepath, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)

        for row in reader:
            ratio_value = row.get("p_over_w_ratio", row.get("pw_ratio", ""))

            jobs.append({
                "job_id": row["job_id"],
                "product": row["product"],
                "operation_type": row["operation_type"],
                "processing_time": int(row["processing_time"]),
                "arrival_time": int(row["arrival_time"]),
                "due_date": int(row["due_date"]),
                "priority_weight": int(row["priority_weight"]),
                "p_over_w_ratio": float(ratio_value),
            })

    return jobs


# ──────────────────────────────────────────────
# Runner for CSV file
# ──────────────────────────────────────────────

def run(filepath: str) -> tuple[list[dict], dict, float]:
    """
    Load a CSV dataset, execute FIFO, and return results.

    This is kept for compatibility with the original code.
    """
    jobs = load_jobs_from_csv(filepath)

    return run_fifo(jobs)


# ──────────────────────────────────────────────
# Print Helper
# ──────────────────────────────────────────────

def print_fifo_results(results: list[dict], metrics: dict, runtime: float) -> None:
    """
    Print FIFO scheduling results.
    """
    print(f"\n{'=' * 50}")
    print("  FIFO Scheduling Results")
    print(f"{'=' * 50}")
    print(f"  {'#':<4} {'Job ID':<8} {'Start':>7} {'Cj':>7} "
          f"{'Wait':>6} {'Tard':>6}")
    print(f"  {'-' * 44}")

    for r in results:
        print(f"  {r['seq']:<4} {r['job_id']:<8} "
              f"{r['start_time']:>7} {r['completion_time']:>7} "
              f"{r['waiting_time']:>6} {r['tardiness']:>6}")

    print(f"\n  Total Completion Time  ΣCj : {metrics['total_Cj']}")
    print(f"  Avg Completion Time         : {metrics['avg_completion_time']}")
    print(f"  Avg Waiting Time            : {metrics['avg_waiting_time']}")
    print(f"  Total Flow Time             : {metrics['total_flow_time']}")
    print(f"  Total Tardiness             : {metrics['total_tardiness']}")
    print(f"  Tardy Jobs                  : {metrics['tardy_jobs']}")
    print(f"  Makespan                    : {metrics['makespan']}")
    print(f"  Big-O                       : {metrics['big_o']}")
    print(f"  Runtime                     : {runtime} ms")
    print(f"{'=' * 50}\n")


# ──────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────

if __name__ == "__main__":
    import sys
    import os

    # Case 1. Run with CSV file path
    if len(sys.argv) > 1:
        dataset = sys.argv[1]

        if not os.path.exists(dataset):
            print(f"[ERROR] File not found: {dataset}")
            sys.exit(1)

        results, metrics, runtime = run(dataset)
        print_fifo_results(results, metrics, runtime)

    # Case 2. No CSV file path: guide for Team 7 dataset usage
    else:
        print("FIFO module is ready.")
        print("Use this module with Team 7 dataset code as follows:")
        print()
        print("from small_dataset_functional_with_ratio import get_small_jobs")
        print("from fifo_final import run_fifo")
        print()
        print("jobs = get_small_jobs()")
        print("results, metrics, runtime = run_fifo(jobs)")
