"""
WSPT (Weighted Shortest Processing Time) Scheduling
=====================================================
Dispatching Rule : Among all available jobs (arrival_time <= current_time),
                   process the one with the smallest p / w ratio first,
                   where p = processing_time, w = priority_weight.
                   Ties broken by job_id.
Objective        : Weighted Total Completion Time ΣwjCj
                   and comparison based on Total Completion Time ΣCj
Data Structure   : List-based dispatching
Time Complexity  : O(n²) worst-case
                   — outer dispatch loop: O(n)
                   — availability filter per step: O(n)
Space Complexity : O(n)

Note
----
WSPT (Smith's Rule) is optimal for 1||ΣwjCj without release times.
With release times it is a heuristic.

This version is modified to match Team 7 dataset files:
- Input data structure: list of dictionaries
- Ratio column name: p_over_w_ratio
- Can run directly with small_jobs or large_jobs generated by Team 7 dataset code
"""

import csv
import time


# ──────────────────────────────────────────────
# Helper: Get p_over_w_ratio safely
# ──────────────────────────────────────────────

def get_p_over_w_ratio(job: dict) -> float:
    """
    Return p_over_w_ratio from a job dictionary.

    Team 7 final dataset uses 'p_over_w_ratio'.
    This helper also supports old 'pw_ratio' only for backward compatibility.
    """
    if "p_over_w_ratio" in job:
        return job["p_over_w_ratio"]

    if "pw_ratio" in job:
        return job["pw_ratio"]

    return round(job["processing_time"] / job["priority_weight"], 2)


# ──────────────────────────────────────────────
# Core Algorithm
# ──────────────────────────────────────────────

def wspt(jobs: list[dict]) -> list[dict]:
    """
    Run WSPT scheduling with release times on a list of jobs.

    Parameters
    ----------
    jobs : list of dict
        Each dict must have keys:
            job_id, product, operation_type, processing_time,
            arrival_time, due_date, priority_weight, p_over_w_ratio

    Returns
    -------
    list of dict
        Scheduled results with added fields:
            seq, start_time, completion_time,
            waiting_time, flow_time, tardiness,
            weighted_completion
    """
    remaining = jobs[:]
    current_time = 0
    results = []
    seq = 1

    while remaining:
        available = [j for j in remaining if j["arrival_time"] <= current_time]

        if not available:
            current_time = min(j["arrival_time"] for j in remaining)
            available = [j for j in remaining if j["arrival_time"] <= current_time]

        # Pick job with smallest p/w ratio; tie-break by job_id
        job = min(available, key=lambda j: (get_p_over_w_ratio(j), j["job_id"]))
        remaining.remove(job)

        start = max(current_time, job["arrival_time"])
        end = start + job["processing_time"]
        current_time = end

        results.append({
            "seq": seq,
            "job_id": job["job_id"],
            "product": job["product"],
            "operation_type": job["operation_type"],
            "processing_time": job["processing_time"],
            "arrival_time": job["arrival_time"],
            "due_date": job["due_date"],
            "priority_weight": job["priority_weight"],
            "p_over_w_ratio": get_p_over_w_ratio(job),
            "start_time": start,
            "completion_time": end,
            "waiting_time": start - job["arrival_time"],
            "flow_time": end - job["arrival_time"],
            "tardiness": max(0, end - job["due_date"]),
            "weighted_completion": job["priority_weight"] * end,
        })
        seq += 1

    return results


# ──────────────────────────────────────────────
# Metrics Helper
# ──────────────────────────────────────────────

def compute_metrics(results: list[dict]) -> dict:
    """
    Compute summary metrics for WSPT results.
    """
    n = len(results)

    return {
        "algorithm": "WSPT",
        "n_jobs": n,
        "total_Cj": sum(r["completion_time"] for r in results),
        "total_wCj": sum(r["weighted_completion"] for r in results),
        "avg_completion_time": round(sum(r["completion_time"] for r in results) / n, 2),
        "avg_waiting_time": round(sum(r["waiting_time"] for r in results) / n, 2),
        "total_flow_time": sum(r["flow_time"] for r in results),
        "avg_flow_time": round(sum(r["flow_time"] for r in results) / n, 2),
        "total_tardiness": sum(r["tardiness"] for r in results),
        "tardy_jobs": sum(1 for r in results if r["tardiness"] > 0),
        "makespan": max(r["completion_time"] for r in results),
        "big_o": "O(n^2)",
    }


# ──────────────────────────────────────────────
# Runner for Team 7 list[dict] dataset
# ──────────────────────────────────────────────

def run_wspt(jobs: list[dict]) -> tuple[list[dict], dict, float]:
    """
    Execute WSPT using a list of job dictionaries.

    This function is recommended for Team 7 final project because
    small_dataset and large_dataset are Python list[dict] data.
    """
    t0 = time.perf_counter()
    results = wspt(jobs)
    runtime = (time.perf_counter() - t0) * 1000

    metrics = compute_metrics(results)
    metrics["runtime_ms"] = round(runtime, 4)

    return results, metrics, round(runtime, 4)


# ──────────────────────────────────────────────
# Optional CSV Loader
# ──────────────────────────────────────────────

def load_jobs_from_csv(filepath: str) -> list[dict]:
    """
    Load job data from CSV.

    Expected ratio column:
        p_over_w_ratio

    For backward compatibility, old column name 'pw_ratio' is also accepted.
    """
    jobs = []

    with open(filepath, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)

        for row in reader:
            ratio_value = row.get("p_over_w_ratio", row.get("pw_ratio", ""))

            jobs.append({
                "job_id": row["job_id"],
                "product": row["product"],
                "operation_type": row["operation_type"],
                "processing_time": int(row["processing_time"]),
                "arrival_time": int(row["arrival_time"]),
                "due_date": int(row["due_date"]),
                "priority_weight": int(row["priority_weight"]),
                "p_over_w_ratio": float(ratio_value),
            })

    return jobs


# ──────────────────────────────────────────────
# Runner for CSV file
# ──────────────────────────────────────────────

def run(filepath: str) -> tuple[list[dict], dict, float]:
    """
    Load a CSV dataset, execute WSPT, and return results.

    This is kept for compatibility with the original code.
    """
    jobs = load_jobs_from_csv(filepath)

    return run_wspt(jobs)


# ──────────────────────────────────────────────
# Print Helper
# ──────────────────────────────────────────────

def print_wspt_results(results: list[dict], metrics: dict, runtime: float) -> None:
    """
    Print WSPT scheduling results.
    """
    print(f"\n{'=' * 50}")
    print("  WSPT Scheduling Results")
    print(f"{'=' * 50}")
    print(f"  {'#':<4} {'Job ID':<8} {'Start':>7} {'Cj':>7} "
          f"{'wCj':>8} {'Wait':>6} {'Tard':>6}")
    print(f"  {'-' * 50}")

    for r in results:
        print(f"  {r['seq']:<4} {r['job_id']:<8} "
              f"{r['start_time']:>7} {r['completion_time']:>7} "
              f"{r['weighted_completion']:>8} "
              f"{r['waiting_time']:>6} {r['tardiness']:>6}")

    print(f"\n  Total Completion Time  ΣCj  : {metrics['total_Cj']}")
    print(f"  Weighted Completion Time ΣwCj: {metrics['total_wCj']}")
    print(f"  Avg Completion Time          : {metrics['avg_completion_time']}")
    print(f"  Avg Waiting Time             : {metrics['avg_waiting_time']}")
    print(f"  Total Flow Time              : {metrics['total_flow_time']}")
    print(f"  Total Tardiness              : {metrics['total_tardiness']}")
    print(f"  Tardy Jobs                   : {metrics['tardy_jobs']}")
    print(f"  Makespan                     : {metrics['makespan']}")
    print(f"  Big-O                        : {metrics['big_o']}")
    print(f"  Runtime                      : {runtime} ms")
    print(f"{'=' * 50}\n")


# ──────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────

if __name__ == "__main__":
    import sys
    import os

    # Case 1. Run with CSV file path
    if len(sys.argv) > 1:
        dataset = sys.argv[1]

        if not os.path.exists(dataset):
            print(f"[ERROR] File not found: {dataset}")
            sys.exit(1)

        results, metrics, runtime = run(dataset)
        print_wspt_results(results, metrics, runtime)

    # Case 2. No CSV file path: guide for Team 7 dataset usage
    else:
        print("WSPT module is ready.")
        print("Use this module with Team 7 dataset code as follows:")
        print()
        print("from small_dataset_functional_with_ratio import get_small_jobs")
        print("from wspt_final import run_wspt")
        print()
        print("jobs = get_small_jobs()")
        print("results, metrics, runtime = run_wspt(jobs)")
